def english_to_french_translator(text:str):
    match text:
        case "school":
            return "école"
        case "kitchen":
            return "cuisine"
        case "chicken":
            return "poulet"
        case "bag":
            return "sac"
        case "bed":
            return "lit"
        case "church":
            return "eglise"
        case "man":
            return "homme"
        case "woman":
            return "femme"
        case "slave":
            return "esclave"
        case "love":
            return "amour"